# Generated by Django 5.0.6 on 2024-06-29 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_rename_name_destination_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='name',
            new_name='name2',
        ),
    ]
