# Generated by Django 5.0.6 on 2024-07-11 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_category_alter_destination_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={},
        ),
    ]
