# Generated by Django 5.0.6 on 2024-07-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0008_ingredient_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='foods',
            field=models.ManyToManyField(blank=True, to='tour.food'),
        ),
    ]
