# Generated by Django 5.0.6 on 2024-07-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0009_tour_foods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='foods',
        ),
        migrations.AddField(
            model_name='food',
            name='foods',
            field=models.ManyToManyField(blank=True, to='tour.tour'),
        ),
    ]
