# Generated by Django 5.0.6 on 2024-07-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0010_remove_tour_foods_food_foods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='foods',
        ),
        migrations.AddField(
            model_name='tour',
            name='foods',
            field=models.ManyToManyField(blank=True, to='tour.food'),
        ),
    ]
