# Generated by Django 5.0.6 on 2024-07-13 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0011_remove_food_foods_tour_foods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='food_time',
        ),
        migrations.RemoveField(
            model_name='food',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='food',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='foods',
        ),
        migrations.AddField(
            model_name='food',
            name='breakfast',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='dinner',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='has_breakfast',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='food',
            name='has_dinner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food',
            name='has_lunch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='food',
            name='lunch',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='tour',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food', to='tour.tour'),
        ),
    ]
