# Generated by Django 5.0.6 on 2024-07-13 15:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0012_remove_food_food_time_remove_food_ingredients_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('stars', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/hotels/')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('tour', models.ManyToManyField(blank=True, related_name='hotel', to='tour.tour')),
                ('facilities', models.ManyToManyField(blank=True, to='tour.hotelfacility')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
