# Generated by Django 5.0.6 on 2024-07-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0013_hotelfacility_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='tour',
        ),
        migrations.AddField(
            model_name='tour',
            name='hotels',
            field=models.ManyToManyField(blank=True, to='tour.hotel'),
        ),
    ]
