# Generated by Django 5.0.6 on 2024-07-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0014_remove_hotel_tour_tour_hotels'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='x',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
