# Generated by Django 5.0.6 on 2024-07-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0015_tour_x'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='x',
        ),
        migrations.AddField(
            model_name='tour',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
