# Generated by Django 5.0.6 on 2024-07-18 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0018_review_tour_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='report',
        ),
    ]
