# Generated by Django 5.0.6 on 2024-07-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0019_rename_text_review_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='report',
            field=models.TextField(blank=True, null=True),
        ),
    ]
