# Generated by Django 5.0.6 on 2024-07-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0020_alter_review_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='reviews',
        ),
        migrations.AddField(
            model_name='review',
            name='tours',
            field=models.ManyToManyField(blank=True, to='tour.tour'),
        ),
    ]
