# Generated by Django 5.0.6 on 2024-07-18 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0021_remove_tour_reviews_review_tours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='tours',
        ),
        migrations.AddField(
            model_name='review',
            name='tours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tour.tour'),
        ),
    ]
