# Generated by Django 5.0.6 on 2024-07-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0022_remove_review_tours_review_tours'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
