# Generated by Django 5.0.6 on 2024-07-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0025_review_rating_alter_review_tours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
